// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyEQupl9aSw2jxNWJpaHw2SMOzRoInDU',
    appId: '1:672409292297:web:dfd5a3dd65da96486332d8',
    messagingSenderId: '672409292297',
    projectId: 'hydraulic-store',
    authDomain: 'hydraulic-store.firebaseapp.com',
    storageBucket: 'hydraulic-store.firebasestorage.app',
    measurementId: 'G-DNYFDQES87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRt_4UDllutm0WcOiMC7D1WypCmyHiy8',
    appId: '1:672409292297:android:c9825f449d4f6fd76332d8',
    messagingSenderId: '672409292297',
    projectId: 'hydraulic-store',
    storageBucket: 'hydraulic-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1oBL5SS3-DuUC1fKPRHvHvaxbvVV2pr4',
    appId: '1:672409292297:ios:e904e54da67186556332d8',
    messagingSenderId: '672409292297',
    projectId: 'hydraulic-store',
    storageBucket: 'hydraulic-store.firebasestorage.app',
    iosClientId: '672409292297-spo8m6aks1qaqpilucb0dq726b0butpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydraulicstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1oBL5SS3-DuUC1fKPRHvHvaxbvVV2pr4',
    appId: '1:672409292297:ios:e904e54da67186556332d8',
    messagingSenderId: '672409292297',
    projectId: 'hydraulic-store',
    storageBucket: 'hydraulic-store.firebasestorage.app',
    iosClientId: '672409292297-spo8m6aks1qaqpilucb0dq726b0butpi.apps.googleusercontent.com',
    iosBundleId: 'com.example.hydraulicstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbyEQupl9aSw2jxNWJpaHw2SMOzRoInDU',
    appId: '1:672409292297:web:a6499cb1b863e3266332d8',
    messagingSenderId: '672409292297',
    projectId: 'hydraulic-store',
    authDomain: 'hydraulic-store.firebaseapp.com',
    storageBucket: 'hydraulic-store.firebasestorage.app',
    measurementId: 'G-50FDNR0T4P',
  );

}